name: build and run tests


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build AgileResultsMVC
        shell: bash
        run: |
          cd src
          dotnet restore "AgileResultsMVC.sln"
          dotnet build --no-restore